name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install Dependencies
        run: flutter pub get

      - name: Install Dependencies for Example
        working-directory: example
        run: flutter pub get

      - name: Build Web from Example
        working-directory: example
        run: flutter build web --release

      - name: Add .nojekyll
        run: echo > example/build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.sketch_flow_secret_key }}
          publish_dir: example/build/web
          publish_branch: gh-pages
